// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ4aLtks9VGoVMRFiSi4dmA8CNcbu5CLQ',
    appId: '1:503233408400:web:9f3b12ce58a3c3752bd715',
    messagingSenderId: '503233408400',
    projectId: 'app-store-deed8',
    authDomain: 'app-store-deed8.firebaseapp.com',
    storageBucket: 'app-store-deed8.firebasestorage.app',
    measurementId: 'G-6961WQYW9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDEh7mHUxenhooQkDuIU4pglnD4Pp9P14',
    appId: '1:503233408400:android:09680347c7b060912bd715',
    messagingSenderId: '503233408400',
    projectId: 'app-store-deed8',
    storageBucket: 'app-store-deed8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ4aLtks9VGoVMRFiSi4dmA8CNcbu5CLQ',
    appId: '1:503233408400:web:465ee3b1cdb870072bd715',
    messagingSenderId: '503233408400',
    projectId: 'app-store-deed8',
    authDomain: 'app-store-deed8.firebaseapp.com',
    storageBucket: 'app-store-deed8.firebasestorage.app',
    measurementId: 'G-4NJG4VC3C4',
  );
}
